// Zotero user.js — applied to the active profile by scripts/apply-config.sh.
// Settings here are re-asserted on every Zotero startup.
//
// NOT included on purpose: extensions.zotero.zotero-mcp-plugin.mcp.server.authToken
// (secret — generated by the plugin on first launch; export to .env after install).

// === zotero-mcp-claude-code plugin ===

// MCP HTTP server: loopback only. Under network_mode: host the container
// loopback IS the host loopback, so binding 127.0.0.1 is enough for the host
// to reach :23120 — allowRemote=true (0.0.0.0) is never needed and violates
// the host rule that only sshd and the system nginx face the network.
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.server.allowRemote", false);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.server.requireAuth", true);

// All write scopes enabled. Remove or flip to false to restrict the agent.
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.bulk",        true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.collections", true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.delete",      true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.import",      true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.metadata",    true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.notes",       true);
user_pref("extensions.zotero.zotero-mcp-plugin.mcp.write.tags",        true);

// AI / content shaping defaults (mirrors the plugin's UI defaults — kept here
// so they survive a profile rebuild).
user_pref("extensions.zotero.zotero-mcp-plugin.ai.maxTokens",          10000);
user_pref("extensions.zotero.zotero-mcp-plugin.content.mode",          "standard");
user_pref("extensions.zotero.zotero-mcp-plugin.custom.enableCompression",       true);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.includeWebpage",          true);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.keywordCount",            5);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.maxAnnotationsPerRequest", 50);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.maxAttachments",          10);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.maxContentLength",        3000);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.maxNotes",                15);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.searchItemLimit",         100);
user_pref("extensions.zotero.zotero-mcp-plugin.custom.smartTruncateLength",     200);
user_pref("extensions.zotero.zotero-mcp-plugin.semantic.autoUpdate",            false);
user_pref("extensions.zotero.zotero-mcp-plugin.text.preserveEmphasis",          false);
user_pref("extensions.zotero.zotero-mcp-plugin.text.preserveFormatting",        true);
user_pref("extensions.zotero.zotero-mcp-plugin.text.preserveHeadings",          true);
user_pref("extensions.zotero.zotero-mcp-plugin.text.preserveLists",             true);
user_pref("extensions.zotero.zotero-mcp-plugin.ui.includeMetadata",             true);
